language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pycodestyle pyflakes
script:
  - pycodestyle --ignore=E501,W503 snallygaster setup.py
  - pyflakes snallygaster setup.py
